# Claude Code Power User — Shell Aliases
# Source this file from your .bashrc:
#   source ~/.bash_aliases  (or wherever you put this)

# System
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cls='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias mkdir='mkdir -p'
alias df='df -h'
alias du='du -h'
alias free='free -m'
alias reload='source ~/.bashrc'

# Git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gst='git status'
alias gc='git commit -m'
alias gca='git commit -am'
alias gcl='git clone'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gp='git push'
alias gpl='git pull'
alias gf='git fetch'
alias gb='git branch'
alias gm='git merge'
alias gd='git diff'
alias gl='git log --oneline --graph --decorate'
alias glog='git log --oneline --graph --decorate --all'
alias grm='git remote'
alias grv='git remote -v'
alias grs='git reset'
alias grsh='git reset --hard'
alias grss='git reset --soft'
alias gs='git stash'
alias gsp='git stash pop'
alias gsl='git stash list'

# Python virtual environment
alias py='python3'
alias pip='pip3'
alias pvenv='python -m venv'
alias create-venv='python3 -m venv .venv'
alias a='source .venv/bin/activate'
alias d='deactivate'
alias pip-upgrade='pip install --upgrade pip'
alias pip-install='pip install -r requirements.txt'
alias pip-freeze='pip freeze > requirements.txt'
alias pip-list='pip list'
alias django-run='python manage.py runserver'
alias django-migrate='python manage.py migrate'
alias django-makemigrations='python manage.py makemigrations'
alias django-shell='python manage.py shell'
alias jupyter='jupyter notebook'

# Quick project setup
alias setup-django='create-venv && a && pip install django && django-admin startproject'
alias setup-flask='create-venv && a && pip install flask && touch app.py'
alias setup-fastapi='create-venv && a && pip install fastapi uvicorn && touch main.py'

# File operations
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias rmf='rm -rf'
alias untar='tar -zxvf'
alias wget-dir='wget -r -np -nd'

# Network
alias myip='curl http://ipecho.net/plain; echo'
alias ping='ping -c 5'
alias ports='netstat -tulanp'
alias listen='lsof -i -P | grep LISTEN'
alias header='curl -I'

# Process management
alias psa='ps aux'
alias psg='ps aux | grep'
alias psm='ps aux | sort -rn -k 4 | head'
alias psc='ps aux | sort -rn -k 3 | head'
alias kill9='kill -9'
alias killall9='killall -9'

# Docker
alias dc='docker-compose'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drmi='docker rmi'
alias drm='docker rm'
alias dst='docker start'
alias dsp='docker stop'
alias dex='docker exec -it'
alias dlog='docker logs'
alias dprune='docker system prune -af'
alias dcup='docker-compose up -d'
alias dcdown='docker-compose down'
alias dcrestart='docker-compose restart'
alias dclogs='docker-compose logs -f'

# System info
alias cpuinfo='lscpu'
alias meminfo='free -h'
alias diskinfo='df -h'

# Compression
alias targz='tar -czvf'
alias untargz='tar -xzvf'
alias untarbz='tar -xjvf'

# Quick server
alias http-server='python3 -m http.server'

# Date and time
alias now='date +"%T"'
alias nowdate='date +"%d-%m-%Y"'
alias today='date +"%A, %B %-d, %Y"'
alias week='date +%V'

# Misc
alias h='history'
alias c='clear'
alias path='echo -e ${PATH//:/\\n}'
alias mem='free -h | grep -v "Swap"'
alias catn='cat -n'
alias open='xdg-open'
alias clip='xclip -selection clipboard'
alias paste='xclip -selection clipboard -o'
alias genpass='openssl rand -base64 20'
alias genpass-strong='openssl rand -base64 32'
alias edit='gedit'
alias code='codium .'

# claude-mem worker (added by claude-mem plugin install)
# alias claude-mem='...'  # regenerated by the plugin; do not hardcode here

# Headroom + DeepSeek
# headroom wrap claude starts the local proxy and launches Claude Code through it.
# settings.local.json points ANTHROPIC_BASE_URL to the proxy (127.0.0.1:8787).
alias claude-default='unset CLAUDE_API_KEY && unset CLAUDE_BASE_URL && headroom wrap claude'
alias claude-default-continue='unset CLAUDE_API_KEY && unset CLAUDE_BASE_URL && headroom wrap claude -- -c'
alias claude-deepseek='export CLAUDE_API_KEY="$DEEPSEEK_API_KEY" && export CLAUDE_BASE_URL="https://api.deepseek.com/v1" && headroom wrap claude'
alias claude-deepseek-continue='export CLAUDE_API_KEY="$DEEPSEEK_API_KEY" && export CLAUDE_BASE_URL="https://api.deepseek.com/v1" && headroom wrap claude -- -c'
